- name: Test custom Ansible module - Step 1
  hosts: localhost
  connection: local  # Esegui i task localmente
  gather_facts: false  # Disabilita la raccolta automatica dei facts
  tasks:
    - name: Gather user and group facts (Step 1)
      user_group_facts_step1:
        include_users: true
        include_groups: true

    - name: Debug output
      debug:
        var: ansible_facts
